services:
  - type: web
    name: moxie-backend
    env: docker
    plan: free
    healthCheckPath: /api/auth/login # or a custom /health endpoint if created
    envVars:
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SQLALCHEMY_DATABASE_URI
        # User needs to put their Aiven connection string here
        sync: false
